import { useState, useCallback } from "react";
import { invoke } from "@tauri-apps/api/core";
import type { AppConfig, ParsedLog } from "../App";
import { pickFile } from "../lib/tauri-bridge";
import { fetchKnownIssues, fetchAllModKnownIssues, type KnownIssue } from "../lib/forge-data";
import { readGuiLog, clearGuiLog, getGuiLogPath } from "../lib/gui-logger";

/** Result from Rust parse_debug_file command */
interface DebugParseSummary {
  weidu_version: string | null;
  errors: DebugIssue[];
  warnings: DebugIssue[];
  success_count: number;
  installed_with_warnings: number;
  success_sample: string[];
  total_lines: number;
  file_size_mb: number;
}

interface DebugIssue {
  line_num: number;
  category: string;
  message: string;
}

/** Display result with known issue matching */
interface DebugResult {
  summary: DebugParseSummary;
  matched: { issue: DebugIssue; known: KnownIssue }[];
  unmatched: DebugIssue[];
}

function matchKnownIssues(
  entries: DebugIssue[],
  knownIssues: KnownIssue[],
): { matched: DebugResult["matched"]; unmatched: DebugIssue[] } {
  const matched: DebugResult["matched"] = [];
  const unmatched: DebugIssue[] = [];

  for (const issue of entries) {
    let found = false;
    for (const known of knownIssues) {
      try {
        if (new RegExp(known.pattern, "i").test(issue.message)) {
          matched.push({ issue, known });
          found = true;
          break;
        }
      } catch {
        // Invalid regex, skip
      }
    }
    if (!found) unmatched.push(issue);
  }
  return { matched, unmatched };
}

function generateBugReport(result: DebugResult): string {
  const { summary } = result;
  const lines: string[] = [];
  lines.push("## Bug Report");
  lines.push("");
  if (summary.weidu_version) lines.push(`**WeiDU Version:** ${summary.weidu_version}`);
  lines.push(`**File:** ${summary.file_size_mb} MB, ${summary.total_lines.toLocaleString()} lines`);
  lines.push(`**Errors:** ${summary.errors.length}`);
  lines.push(`**Warnings:** ${summary.warnings.length}`);
  lines.push(`**Total Installed:** ${summary.success_count} (${summary.success_count - summary.installed_with_warnings} clean, ${summary.installed_with_warnings} with warnings)`);
  lines.push("");

  if (summary.errors.length > 0) {
    lines.push("### Errors");
    for (const e of summary.errors.slice(0, 30)) {
      lines.push(`- \`${e.message.slice(0, 150)}\``);
    }
    lines.push("");
  }

  if (result.matched.length > 0) {
    // Group by description for the report too
    const groups = new Map<string, { known: KnownIssue; count: number }>();
    for (const { known } of result.matched) {
      const existing = groups.get(known.description);
      if (existing) {
        existing.count++;
      } else {
        groups.set(known.description, { known, count: 1 });
      }
    }
    lines.push(`### Known Issues Found (${groups.size} types, ${result.matched.length} occurrences)`);
    for (const [, { known, count }] of groups) {
      const countStr = count > 1 ? ` (${count}x)` : "";
      lines.push(`- **[${known.severity.toUpperCase()}] ${known.description}**${countStr}`);
      lines.push(`  - Workaround: ${known.workaround}`);
      if (known.forum) lines.push(`  - Discussion: ${known.forum}`);
    }
    lines.push("");
  }

  if (summary.warnings.length > 0) {
    // Group warnings by message similarity (first 80 chars as key)
    const warnGroups = new Map<string, { sample: string; count: number }>();
    for (const w of summary.warnings) {
      const key = w.message.slice(0, 80).replace(/\[.*?\]/g, "[...]").replace(/\d+/g, "N");
      const existing = warnGroups.get(key);
      if (existing) {
        existing.count++;
      } else {
        warnGroups.set(key, { sample: w.message.slice(0, 150), count: 1 });
      }
    }
    lines.push(`### Warnings (${warnGroups.size} types, ${summary.warnings.length} occurrences)`);
    for (const [, { sample, count }] of warnGroups) {
      const countStr = count > 1 ? ` (${count}x)` : "";
      lines.push(`- \`${sample}\`${countStr}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by EET Mod Runner*");
  return lines.join("\n");
}

interface Props {
  config: AppConfig;
  forgeOnline: boolean | null;
  parsedLog: ParsedLog | null;
}

export default function DebugPanel({ config, forgeOnline, parsedLog }: Props) {
  const [result, setResult] = useState<DebugResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [loadingMsg, setLoadingMsg] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [reportCopied, setReportCopied] = useState(false);

  const loadDebugFile = useCallback(async () => {
    let path: string | null = null;
    try {
      path = await pickFile("Select Debug Log", [
        { name: "Debug Logs", extensions: ["debug", "log", "txt"] },
        { name: "All Files", extensions: ["*"] },
      ]);
    } catch (e) {
      setError(`Failed to open file picker: ${e}`);
      return;
    }
    if (!path) return;

    setLoading(true);
    setError(null);
    setLoadingMsg("Parsing debug log (this may take a moment for large files)...");

    try {
      // Parse in Rust backend — handles 500MB+ files without freezing
      const summary = await invoke<DebugParseSummary>("parse_debug_file", { path });

      setLoadingMsg("Matching against known issues...");

      // Combine global known_issues.json + per-mod ki fields
      let knownIssues: KnownIssue[] = [];
      if (forgeOnline) {
        const baseUrl = config.forge_data_url || "https://anprionsa.github.io/eet-mod-forge";

        // 1. Fetch global patterns
        try {
          const global = await fetchKnownIssues(baseUrl);
          knownIssues.push(...global);
        } catch {
          // Offline
        }

        // 2. Extract unique mod names from errors/warnings to fetch per-mod ki
        const modNames = new Set<string>();
        for (const issue of [...summary.errors, ...summary.warnings]) {
          // Try to extract mod name from messages like "ERROR Installing [ModName]"
          const bracketMatch = issue.message.match(/\[([^\]]+)\]/);
          if (bracketMatch) {
            modNames.add(bracketMatch[1].toLowerCase().replace(/\s+/g, "_"));
          }
          // Also try the category field which often has the mod tp2 name
          if (issue.category) {
            modNames.add(issue.category.toLowerCase());
          }
        }
        // Also extract from success samples
        for (const s of summary.success_sample) {
          const m = s.match(/SUCCESSFULLY INSTALLED\s+(.*)/i);
          if (m) {
            const name = m[1].trim().split(/\s*->\s*/)[0].toLowerCase().replace(/\s+/g, "_");
            modNames.add(name);
          }
        }

        setLoadingMsg(`Fetching known issues for ${modNames.size} mods...`);

        try {
          const perMod = await fetchAllModKnownIssues(baseUrl, [...modNames]);
          knownIssues.push(...perMod);
        } catch {
          // Per-mod fetch failed, continue with global only
        }
      }

      const allIssues = [...summary.errors, ...summary.warnings];
      const { matched, unmatched } = matchKnownIssues(allIssues, knownIssues);

      setResult({ summary, matched, unmatched });
    } catch (e) {
      setError(`Failed to parse debug file: ${e}`);
    } finally {
      setLoading(false);
      setLoadingMsg("");
    }
  }, [config.forge_data_url, forgeOnline]);

  const copyReport = useCallback(() => {
    if (!result) return;
    const report = generateBugReport(result);
    navigator.clipboard.writeText(report).then(() => {
      setReportCopied(true);
      setTimeout(() => setReportCopied(false), 2000);
    });
  }, [result]);

  return (
    <div>
      <h2>Debug Analysis</h2>
      <p style={{ color: "var(--txd)", marginBottom: 20, fontSize: 13 }}>
        Load a WeiDU debug log (WSETUP.DEBUG, Setup-*.debug) to diagnose
        installation issues. Handles files up to 500MB+.
      </p>

      {/* Drop zone — shown when no result and not loading */}
      {!result && !loading && (
        <div className="drop-zone" onClick={loadDebugFile}>
          <div style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: "0.5px", color: "var(--gold)", marginBottom: 8, fontWeight: 600 }}>
            WeiDU Debug Log
          </div>
          <div className="icon">{"\u2B07"}</div>
          <div>WSETUP.DEBUG or Setup-*.debug</div>
          <div style={{ fontSize: 11, marginTop: 4, color: "var(--txd)" }}>
            Click to select a debug log file
          </div>
        </div>
      )}

      {/* Loading indicator */}
      {loading && (
        <div className="install-dashboard" style={{ textAlign: "center", padding: 32 }}>
          <div style={{ color: "var(--gold)", fontSize: 16, fontWeight: 600, marginBottom: 8 }}>
            Parsing...
          </div>
          <div style={{ color: "var(--txd)", fontSize: 13 }}>{loadingMsg}</div>
          <div className="progress-bar" style={{ height: 4, marginTop: 16 }}>
            <div className="fill" style={{ width: "100%", animation: "none", opacity: 0.5 }} />
          </div>
        </div>
      )}

      {/* Action buttons */}
      {result && (
        <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
          <button className="btn" onClick={loadDebugFile} disabled={loading}>
            Load Different File
          </button>
          <button className="btn" onClick={copyReport}>
            {reportCopied ? "Copied!" : "Copy Bug Report"}
          </button>
        </div>
      )}

      {error && <div className="msg err">{error}</div>}

      {result && (
        <>
          {/* File info */}
          <div className="msg info" style={{ marginBottom: 12 }}>
            {result.summary.weidu_version || "WeiDU version unknown"}
            {" \u2014 "}
            {result.summary.file_size_mb} MB, {result.summary.total_lines.toLocaleString()} lines
          </div>

          {/* Summary cards */}
          <div className="summary-grid">
            <div className="summary-card">
              <div className="number" style={{ color: "var(--grn)" }}>
                {result.summary.success_count}
              </div>
              <div className="label">Total Installed</div>
              <div style={{ fontSize: 10, color: "var(--txd)", marginTop: 4 }}>
                <span style={{ color: "var(--grn)" }}>{result.summary.success_count - result.summary.installed_with_warnings}</span> clean
                {result.summary.installed_with_warnings > 0 && (
                  <span> / <span style={{ color: "var(--org)" }}>{result.summary.installed_with_warnings}</span> with warnings</span>
                )}
              </div>
            </div>
            <div className="summary-card">
              <div className="number" style={{ color: "var(--red)" }}>
                {result.summary.errors.length}
              </div>
              <div className="label">Errors</div>
            </div>
            <div className="summary-card">
              <div className="number" style={{ color: "var(--blu)" }}>
                {result.matched.length}
              </div>
              <div className="label">Known Issues</div>
            </div>
          </div>

          {/* All sections collapsible, starting collapsed */}

          {/* Errors */}
          {result.summary.errors.length > 0 && (
            <CollapsibleSection
              title={`Errors (${result.summary.errors.length})`}
              color="var(--red)"
              defaultOpen={false}
              extra={<CopyButton getText={() => result.summary.errors.map((e) => `L${e.line_num} [${e.category}] ${e.message}`).join("\n")} label="Copy" />}
            >
              <div className="log-output" style={{ maxHeight: 250 }}>
                {result.summary.errors.map((e, i) => (
                  <div key={i} className="log-err">
                    L{e.line_num} [{e.category}] {e.message}
                  </div>
                ))}
              </div>
            </CollapsibleSection>
          )}

          {/* Known issues — grouped by description */}
          {result.matched.length > 0 && (
            <CollapsibleSection
              title={`Known Issues (${result.matched.length} occurrences)`}
              color="var(--blu)"
              defaultOpen={false}
              extra={<CopyButton getText={() => {
                const groups = new Map<string, number>();
                for (const { known } of result.matched) { groups.set(known.description, (groups.get(known.description) || 0) + 1); }
                return [...groups.entries()].map(([desc, n]) => `[${n}x] ${desc}`).join("\n");
              }} label="Copy" />}
            >
              <GroupedKnownIssues matched={result.matched} />
            </CollapsibleSection>
          )}

          {/* Warnings — grouped */}
          {result.summary.warnings.length > 0 && (
            <CollapsibleSection
              title={`Warnings (${result.summary.warnings.length})`}
              color="var(--org)"
              defaultOpen={false}
              extra={<CopyButton getText={() => result.summary.warnings.map((w) => `L${w.line_num} ${w.message}`).join("\n")} label="Copy" />}
            >
              <GroupedWarnings warnings={result.summary.warnings} />
            </CollapsibleSection>
          )}

          {/* Unmatched errors */}
          {result.unmatched.length > 0 && (
            <CollapsibleSection
              title={`Unmatched Issues (${result.unmatched.length})`}
              color="var(--txd)"
              defaultOpen={false}
              extra={
                <CopyButton
                  getText={() =>
                    result.unmatched
                      .map((e) => `L${e.line_num} [${e.category}] ${e.message}`)
                      .join("\n")
                  }
                  label="Copy"
                />
              }
            >
              <div className="log-output" style={{ maxHeight: 200 }}>
                {result.unmatched.map((e, i) => (
                  <div key={i} className={e.category.includes("error") || e.category.includes("failed") ? "log-err" : "log-warn"}>
                    L{e.line_num} [{e.category}] {e.message}
                  </div>
                ))}
              </div>
            </CollapsibleSection>
          )}

          {/* Successful installs sample */}
          {result.summary.success_sample.length > 0 && (
            <CollapsibleSection
              title={`Installed (${result.summary.success_count})`}
              color="var(--grn)"
              defaultOpen={false}
              extra={<CopyButton getText={() => result.summary.success_sample.join("\n")} label="Copy" />}
            >
              <div className="log-output" style={{ maxHeight: 200, fontSize: 11 }}>
                {result.summary.success_sample.map((s, i) => (
                  <div key={i} className="log-ok">{s}</div>
                ))}
                {result.summary.success_count > result.summary.success_sample.length && (
                  <div style={{ color: "var(--txd)", padding: "4px 0" }}>
                    ... and {result.summary.success_count - result.summary.success_sample.length} more
                  </div>
                )}
              </div>
            </CollapsibleSection>
          )}
        </>
      )}

      {/* ── Install Comparison ── */}
      <div style={{ marginTop: 24, borderTop: "1px solid var(--brd)", paddingTop: 16 }}>
        <h2>Install Comparison</h2>
        <p style={{ color: "var(--txd)", marginBottom: 12, fontSize: 13 }}>
          Compare your Forge export against what actually installed. Shows exactly
          which components are missing and which mods failed completely.
        </p>
        <InstallComparison config={config} parsedLog={parsedLog} />
      </div>

      {/* ── GUI Log ── */}
      <div style={{ marginTop: 24, borderTop: "1px solid var(--brd)", paddingTop: 16 }}>
        <h2>GUI Log</h2>
        <p style={{ color: "var(--txd)", marginBottom: 12, fontSize: 13 }}>
          Application-level log for diagnosing GUI issues. Does not contain WeiDU
          or mod_installer output.
        </p>
        <GuiLogViewer />
      </div>
    </div>
  );
}

interface CompareResult {
  export_count: number;
  installed_count: number;
  missing_count: number;
  missing_mods: { mod_name: string; missing_components: string[]; total_in_export: number; installed_count: number }[];
  partial_mods: number;
  completely_missing_mods: number;
}

function InstallComparison({ config, parsedLog }: { config: AppConfig; parsedLog: ParsedLog | null }) {
  const [result, setResult] = useState<CompareResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Use the imported log path from the Import tab if available
  const exportPath = parsedLog?.eetLogPath || null;
  const hasImportedLog = !!exportPath;

  const runComparison = useCallback(async (overridePath?: string) => {
    if (!config.bg2_game_dir) {
      setError("BG2 game directory not configured in Setup.");
      return;
    }

    let path = overridePath || exportPath;

    // If no imported log, ask user to pick one
    if (!path) {
      try {
        path = await pickFile("Select Export WeiDU.log (from Forge)", [
          { name: "WeiDU Log", extensions: ["log", "LOG"] },
          { name: "All Files", extensions: ["*"] },
        ]);
      } catch (e) {
        setError(`Failed to open file picker: ${e}`);
        return;
      }
      if (!path) return;
    }

    setLoading(true);
    setError(null);
    try {
      const r = await invoke<CompareResult>("compare_install_logs", {
        exportLogPath: path,
        gameDir: config.bg2_game_dir,
      });
      setResult(r);
    } catch (e) {
      setError(`Comparison failed: ${e}`);
    } finally {
      setLoading(false);
    }
  }, [config.bg2_game_dir, exportPath]);

  const completely = result?.missing_mods.filter((m) => m.installed_count === 0) || [];
  const partial = result?.missing_mods.filter((m) => m.installed_count > 0) || [];
  const completelyCount = completely.reduce((sum, m) => sum + m.missing_components.length, 0);
  const partialCount = partial.reduce((sum, m) => sum + m.missing_components.length, 0);

  const missingPct = result && result.export_count > 0
    ? Math.round((result.missing_count / result.export_count) * 100)
    : 0;

  return (
    <div>
      {!result && !loading && hasImportedLog && (
        <div style={{ marginBottom: 12 }}>
          <div className="msg info" style={{ marginBottom: 8, fontSize: 12 }}>
            Using imported log from Import tab
          </div>
          <button className="btn btn-primary" onClick={() => runComparison()}>
            Compare Against Installed
          </button>
        </div>
      )}

      {!result && !loading && !hasImportedLog && (
        <div className="drop-zone" onClick={() => runComparison()}>
          <div style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: "0.5px", color: "var(--gold)", marginBottom: 8, fontWeight: 600 }}>
            Export WeiDU.log
          </div>
          <div className="icon">{"\u2B07"}</div>
          <div>Select the WeiDU.log exported from EET Mod Forge</div>
          <div style={{ fontSize: 11, marginTop: 4, color: "var(--txd)" }}>
            Or import logs in the Import tab first
          </div>
        </div>
      )}

      {loading && (
        <div className="install-dashboard" style={{ textAlign: "center", padding: 24 }}>
          <div style={{ color: "var(--gold)", fontWeight: 600 }}>Comparing logs...</div>
        </div>
      )}

      {error && <div className="msg err">{error}</div>}

      {result && (
        <>
          <div style={{ display: "flex", gap: 8, marginBottom: 12 }}>
            <button className="btn" onClick={() => runComparison()} disabled={loading}>
              Re-Compare
            </button>
            <button className="btn" onClick={async () => {
              const path = await pickFile("Select Different Export WeiDU.log", [
                { name: "WeiDU Log", extensions: ["log", "LOG"] },
                { name: "All Files", extensions: ["*"] },
              ]);
              if (path) runComparison(path);
            }} disabled={loading}>
              Compare Different Export
            </button>
          </div>

          <div className="summary-grid">
            <div className="summary-card">
              <div className="number" style={{ color: "var(--txd)" }}>
                {result.export_count}
              </div>
              <div className="label">Exported</div>
            </div>
            <div className="summary-card">
              <div className="number" style={{ color: "var(--grn)" }}>
                {result.installed_count}
              </div>
              <div className="label">Installed</div>
            </div>
            <div className="summary-card">
              <div className="number" style={{ color: "var(--red)" }}>
                {result.missing_count}
              </div>
              <div className="label">Missing ({missingPct}%)</div>
            </div>
          </div>

          {completely.length > 0 && (
            <CollapsibleSection
              title={`Completely Missing (${completely.length} mods, ${completelyCount} components)`}
              color="var(--red)"
              defaultOpen={false}
              extra={<CopyButton getText={() => completely.map((m) => `${m.mod_name} (${m.missing_components.length}/${m.total_in_export}): ${m.missing_components.join(", ")}`).join("\n")} label="Copy" />}
            >
              <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
                {completely.map((mod) => (
                  <div key={mod.mod_name} style={{
                    background: "var(--bg2)", border: "1px solid var(--brd)",
                    borderRadius: 4, padding: "8px 12px", fontSize: 12,
                  }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                      <span style={{ color: "var(--gold)", fontWeight: 600 }}>{mod.mod_name}</span>
                      <span style={{ color: "var(--red)", fontSize: 11 }}>
                        0/{mod.total_in_export} installed
                      </span>
                    </div>
                    <div style={{ color: "var(--txd)", fontSize: 11, marginTop: 4 }}>
                      {mod.missing_components.slice(0, 10).join(" | ")}
                      {mod.missing_components.length > 10 && (
                        <span style={{ color: "var(--txd)", opacity: 0.6 }}>
                          {" "}... and {mod.missing_components.length - 10} more
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </CollapsibleSection>
          )}

          {partial.length > 0 && (
            <CollapsibleSection
              title={`Partially Installed (${partial.length} mods, ${partialCount} missing components)`}
              color="var(--org)"
              defaultOpen={false}
              extra={<CopyButton getText={() => partial.map((m) => `${m.mod_name} (${m.installed_count}/${m.total_in_export} installed, missing ${m.missing_components.length}): ${m.missing_components.join(", ")}`).join("\n")} label="Copy" />}
            >
              <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
                {partial.map((mod) => (
                  <div key={mod.mod_name} style={{
                    background: "var(--bg2)", border: "1px solid var(--brd)",
                    borderRadius: 4, padding: "8px 12px", fontSize: 12,
                  }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                      <span style={{ color: "var(--gold)", fontWeight: 600 }}>{mod.mod_name}</span>
                      <span style={{ color: "var(--org)", fontSize: 11 }}>
                        {mod.installed_count}/{mod.total_in_export} installed
                      </span>
                    </div>
                    <div style={{ color: "var(--txd)", fontSize: 11, marginTop: 4 }}>
                      Missing: {mod.missing_components.slice(0, 8).join(" | ")}
                      {mod.missing_components.length > 8 && (
                        <span style={{ opacity: 0.6 }}>
                          {" "}... and {mod.missing_components.length - 8} more
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </CollapsibleSection>
          )}

          {result.missing_count === 0 && (
            <div className="msg ok" style={{ marginTop: 12 }}>
              All exported components are installed. No missing mods.
            </div>
          )}
        </>
      )}
    </div>
  );
}

function GuiLogViewer() {
  const [logContent, setLogContent] = useState<string | null>(null);
  const [logPath, setLogPath] = useState<string>("");
  const [copied, setCopied] = useState(false);

  const loadLog = useCallback(async () => {
    try {
      const [content, path] = await Promise.all([readGuiLog(), getGuiLogPath()]);
      setLogContent(content);
      setLogPath(path);
    } catch (e) {
      setLogContent(`Failed to read gui.log: ${e}`);
    }
  }, []);

  const copyLog = useCallback(async () => {
    if (!logContent) return;
    await navigator.clipboard.writeText(logContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [logContent]);

  const handleClear = useCallback(async () => {
    try {
      await clearGuiLog();
      setLogContent("");
    } catch (e) {
      setLogContent(`Failed to clear: ${e}`);
    }
  }, []);

  return (
    <div>
      <div style={{ display: "flex", gap: 8, marginBottom: 12 }}>
        <button className="btn btn-primary" onClick={loadLog}>
          {logContent === null ? "Load GUI Log" : "Refresh"}
        </button>
        {logContent !== null && (
          <>
            <button className="btn" onClick={copyLog}>
              {copied ? "Copied!" : "Copy to Clipboard"}
            </button>
            <button className="btn btn-danger" onClick={handleClear}>
              Clear Log
            </button>
          </>
        )}
      </div>
      {logPath && (
        <div style={{ fontSize: 11, color: "var(--txd)", marginBottom: 8 }}>
          File: {logPath}
        </div>
      )}
      {logContent !== null && (
        <div className="log-output" style={{ maxHeight: 300, fontSize: 11 }}>
          {logContent
            ? logContent.split("\n").map((line, i) => (
                <div
                  key={i}
                  className={
                    line.includes("[ERROR]") ? "log-err"
                      : line.includes("[WARN]") ? "log-warn"
                      : line.includes("[INFO]") ? "log-ok"
                      : ""
                  }
                >
                  {line}
                </div>
              ))
            : <div style={{ color: "var(--txd)" }}>Log is empty</div>
          }
        </div>
      )}
    </div>
  );
}

interface GroupedKnown {
  description: string;
  severity: string;
  workaround: string;
  forum?: string;
  occurrences: { issue: DebugIssue; known: KnownIssue }[];
}

function GroupedKnownIssues({ matched }: { matched: DebugResult["matched"] }) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  // Group by description
  const groups: GroupedKnown[] = [];
  const map = new Map<string, GroupedKnown>();
  for (const m of matched) {
    const key = m.known.description;
    if (!map.has(key)) {
      const g: GroupedKnown = {
        description: m.known.description,
        severity: m.known.severity,
        workaround: m.known.workaround,
        forum: m.known.forum,
        occurrences: [],
      };
      map.set(key, g);
      groups.push(g);
    }
    map.get(key)!.occurrences.push(m);
  }

  const uniqueCount = groups.length;
  const totalCount = matched.length;

  return (
    <>
      <h3>Known Issues Found ({uniqueCount} types, {totalCount} occurrences)</h3>
      {groups.map((group) => {
        const isExpanded = expanded.has(group.description);
        const isSingle = group.occurrences.length === 1;
        const toggleExpand = () => {
          setExpanded((prev) => {
            const next = new Set(prev);
            if (next.has(group.description)) next.delete(group.description);
            else next.add(group.description);
            return next;
          });
        };

        return (
          <div key={group.description} style={{
            background: "var(--bg2)", border: "1px solid var(--brd)",
            borderRadius: 4, marginBottom: 6, overflow: "hidden",
          }}>
            {/* Header — always visible */}
            <div
              style={{
                padding: "10px 12px", cursor: isSingle ? "default" : "pointer",
                display: "flex", justifyContent: "space-between", alignItems: "flex-start",
              }}
              onClick={isSingle ? undefined : toggleExpand}
            >
              <div style={{ flex: 1 }}>
                <div style={{
                  color: group.severity === "critical" ? "var(--red)"
                    : group.severity === "warning" ? "var(--org)"
                    : "var(--blu)",
                  fontWeight: 600, fontSize: 13, marginBottom: 4,
                }}>
                  {!isSingle && (
                    <span style={{ fontSize: 10, marginRight: 6, opacity: 0.7 }}>
                      {isExpanded ? "\u25BC" : "\u25B6"}
                    </span>
                  )}
                  [{group.severity.toUpperCase()}] {group.description}
                </div>
                {isSingle && (
                  <div style={{ color: "var(--txd)", fontSize: 11, fontFamily: "monospace", marginBottom: 4 }}>
                    Line {group.occurrences[0].issue.line_num}: {group.occurrences[0].issue.message.slice(0, 120)}
                  </div>
                )}
                <div style={{ color: "var(--grn)", fontSize: 11 }}>
                  Workaround: {group.workaround}
                </div>
                {group.forum && (
                  <div style={{ fontSize: 11, marginTop: 2 }}>
                    <a href={group.forum} style={{ color: "var(--blu)" }} target="_blank" rel="noreferrer"
                      onClick={(e) => e.stopPropagation()}>
                      Forum discussion
                    </a>
                  </div>
                )}
              </div>
              {!isSingle && (
                <span style={{
                  background: "var(--bg3)", color: "var(--txd)", fontSize: 11,
                  padding: "2px 8px", borderRadius: 10, whiteSpace: "nowrap", marginLeft: 8,
                }}>
                  {group.occurrences.length}x
                </span>
              )}
            </div>

            {/* Expanded occurrences */}
            {isExpanded && !isSingle && (
              <div style={{
                borderTop: "1px solid var(--brd)", padding: "6px 12px",
                maxHeight: 200, overflowY: "auto", background: "var(--bg)",
              }}>
                {group.occurrences.map((m, i) => (
                  <div key={i} style={{
                    fontSize: 11, fontFamily: "monospace", color: "var(--txd)",
                    padding: "2px 0", borderBottom: i < group.occurrences.length - 1 ? "1px solid var(--brd)" : "none",
                  }}>
                    L{m.issue.line_num}: {m.issue.message.slice(0, 150)}
                  </div>
                ))}
              </div>
            )}
          </div>
        );
      })}
    </>
  );
}

function CollapsibleSection({ title, color, defaultOpen = false, extra, children }: {
  title: string;
  color: string;
  defaultOpen?: boolean;
  extra?: React.ReactNode;
  children: React.ReactNode;
}) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div style={{ marginBottom: 8 }}>
      <div
        className="log-toggle"
        onClick={() => setOpen(!open)}
        style={{ borderLeft: `3px solid ${color}`, marginBottom: open ? 4 : 0 }}
      >
        <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
          <span style={{ fontSize: 10 }}>{open ? "\u25BC" : "\u25B6"}</span>
          <span style={{ color, fontWeight: 600 }}>{title}</span>
        </span>
        <span style={{ display: "flex", alignItems: "center", gap: 8 }}>
          {extra && <span onClick={(e) => e.stopPropagation()}>{extra}</span>}
          <span style={{ fontSize: 11 }}>{open ? "collapse" : "expand"}</span>
        </span>
      </div>
      {open && <div style={{ paddingLeft: 6, borderLeft: `3px solid ${color}`, borderBottomLeftRadius: 4 }}>{children}</div>}
    </div>
  );
}

function GroupedWarnings({ warnings }: { warnings: DebugIssue[] }) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  // Group warnings by similarity (normalize numbers and bracketed content)
  const groups: { key: string; sample: string; items: DebugIssue[] }[] = [];
  const map = new Map<string, { sample: string; items: DebugIssue[] }>();
  for (const w of warnings) {
    const key = w.message.slice(0, 80).replace(/\[.*?\]/g, "[...]").replace(/\d+/g, "N").replace(/\s+/g, " ");
    if (!map.has(key)) {
      const g = { sample: w.message, items: [] as DebugIssue[] };
      map.set(key, g);
      groups.push({ key, ...g });
    }
    map.get(key)!.items.push(w);
  }

  return (
    <div>
      {groups.map((group) => {
        const isExpanded = expanded.has(group.key);
        const isSingle = group.items.length === 1;
        return (
          <div key={group.key} style={{
            background: "var(--bg2)", border: "1px solid var(--brd)",
            borderRadius: 4, marginBottom: 4, overflow: "hidden",
          }}>
            <div
              style={{
                padding: "6px 10px", cursor: isSingle ? "default" : "pointer",
                display: "flex", justifyContent: "space-between", alignItems: "center",
                fontSize: 12,
              }}
              onClick={isSingle ? undefined : () => {
                setExpanded((prev) => {
                  const next = new Set(prev);
                  if (next.has(group.key)) next.delete(group.key);
                  else next.add(group.key);
                  return next;
                });
              }}
            >
              <span style={{ color: "var(--org)", flex: 1 }}>
                {!isSingle && <span style={{ fontSize: 9, marginRight: 6, opacity: 0.7 }}>{isExpanded ? "\u25BC" : "\u25B6"}</span>}
                {group.sample.slice(0, 120)}
              </span>
              {!isSingle && (
                <span style={{
                  background: "var(--bg3)", color: "var(--txd)", fontSize: 11,
                  padding: "1px 6px", borderRadius: 10, marginLeft: 8, whiteSpace: "nowrap",
                }}>
                  {group.items.length}x
                </span>
              )}
            </div>
            {isExpanded && !isSingle && (
              <div style={{
                borderTop: "1px solid var(--brd)", padding: "4px 10px",
                maxHeight: 150, overflowY: "auto", background: "var(--bg)",
              }}>
                {group.items.map((w, i) => (
                  <div key={i} style={{ fontSize: 11, fontFamily: "monospace", color: "var(--txd)", padding: "1px 0" }}>
                    L{w.line_num}: {w.message.slice(0, 150)}
                  </div>
                ))}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

function CopyButton({ getText, label }: { getText: () => string; label: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      className="btn"
      style={{ fontSize: 11, padding: "4px 10px" }}
      onClick={() => {
        navigator.clipboard.writeText(getText()).then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        });
      }}
    >
      {copied ? "Copied!" : label}
    </button>
  );
}
