(* This file is automatically generated from src/{tparser.gr,tlexer.in,make_tll.ml}.
    DO NOT EDIT THIS BY HAND. *)

{

open Util
open Toldparser

(* Note added due to LGPL terms.

This file was edited by Valerio Bigiani, AKA The Bigg, starting from
6 November 2005. All changes for this file are listed in
diffs/src.dlexer.mll.diff file, as the output of a diff -Bw -c -N command.

It was originally taken from Westley Weimer's WeiDU 185. *)

(*
** Keyword hashtable
*)

let string_of lb = (Lexing.lexeme lb)

let lexicon = Hashtbl.create 211
let _ = List.iter
    (fun (key, token) -> Hashtbl.add lexicon key token)
    [
      ("LOOKUP_IDS_SYMBOL_OF_INT", SET_IDS_SYMBOL_OF_INT) ;
      ("ACTION_DEFINE_ARRAY", ACTION_DEFINE_ARRAY) ;
	    ("ACTION_BASH_FOR", ACTION_BASH_FOR) ;
	    ("ACTION_FOR_EACH", ACTION_FOR_EACH) ;
	    ("ACTION_PHP_EACH", ACTION_PHP_EACH) ;
      ("ACTION_IF", ACTION_IF) ;
      ("ACTION_READLN", ACTION_READLN);
      ("ADD_CRE_ITEM", ADD_CRE_ITEM) ;
      ("ADD_GAME_NPC", PATCH_GAM) ;
      ("ADD_KIT", ADD_KIT) ;
      ("ADD_KNOWN_SPELL", ADD_KNOWN_SPELL) ;
      ("ADD_MEMORIZED_SPELL", ADD_MEMORIZED_SPELL) ;
      ("ADD_MAP_NOTE", ADD_MAP_NOTE);
      ("ADD_MUSIC", ADD_MUSIC) ;
      ("ADD_PROJECTILE", ADD_PROJECTILE) ;
      ("ADD_SPELL", ADD_SPELL) ;
      ("ADD_STORE_ITEM", ADD_STORE_ITEM) ;
      ("AFTER", AFTER) ;
      ("ALLOW_MISSING", ALLOW_MISSING) ;
      ("ALWAYS", ALWAYS) ;
      ("APPEND", APPEND);
      ("APPEND_COL", APPEND_COL);
      ("APPEND_FILE", APPEND_FILE);
      ("APPEND_FILE_EVALUATE", APPEND_FILE_EVALUATE);
      ("APPEND_OUTER", APPEND_OUTER);
      ("APPLY_BCS_PATCH", APPLY_BCS_PATCH) ;
      ("APPLY_BCS_PATCH_OR_COPY", APPLY_BCS_PATCH_OR_COPY) ;
      ("AS", AS) ;
      ("ASK_EVERY_COMPONENT", ASK_EVERY_COMPONENT);
      ("AT_EXIT", AT_EXIT);
      ("AT_INTERACTIVE_EXIT", AT_INTERACTIVE_EXIT) ;
      ("AT_INTERACTIVE_NOW", AT_INTERACTIVE_NOW) ;
      ("AT_INTERACTIVE_UNINSTALL", AT_INTERACTIVE_UNINSTALL) ;
      ("AT_NOW", AT_NOW) ;
      ("AT_UNINSTALL", AT_UNINSTALL) ;
      ("AUTHOR", AUTHOR);
      ("AUTO_TRA", AUTO_TRA);
      ("A_B_P", APPLY_BCS_PATCH) ;
      ("BACKUP", BACKUP) ;
      ("BEFORE", BEFORE) ;
      ("BEGIN", BEGIN) ;
      ("MAKE_BIFF", BIFF) ;
      ("BUT_ONLY_IF_IT_CHANGES", BUT_ONLY_IF_IT_CHANGES);
      ("BUT_ONLY", BUT_ONLY_IF_IT_CHANGES) ;
      ("CASE_INSENSITIVE", CASE_INSENSITIVE) ;
      ("CASE_SENSITIVE", CASE_SENSITIVE) ;
      ("CLEAR_IDS_MAP", CLEAR_IDS_MAP) ;
      ("CLEAR_MEMORY", CLEAR_MEMORY);
      ("CLEAR_ARRAY", PATCH_CLEAR_ARRAY) ;
      ("COMPILE", COMPILE);
      ("COMPILE_BAF_TO_BCS", COMPILE_BAF_TO_BCS);
      ("COMPILE_D_TO_DLG", COMPILE_D_TO_DLG);
      ("COPY", COPY);
      ("COPY_KIT", COPY_KIT);
      ("COPY_ALL_GAM_FILES", COPY_ALL_GAM_FILES);
      ("COPY_EXISTING", COPY_EXISTING);
      ("COPY_EXISTING_REGEXP", COPY_EXISTING_REGEXP);
      ("COPY_LARGE", COPY_LARGE);
      ("COPY_RANDOM", COPY_RANDOM);
      ("COUNT_2DA_ROWS", COUNT_2DA_ROWS) ;
      ("COUNT_2DA_COLS", COUNT_2DA_COLS) ;
      ("COUNT_REGEXP_INSTANCES", COUNT_REGEXP_INSTANCES) ;
      ("DECOMPILE_BCS_TO_BAF", DECOMPILE_BCS_TO_BAF);
      ("DECOMPILE_DLG_TO_D", DECOMPILE_DLG_TO_D);
      ("DEFINE_ACTION_MACRO", DEFINE_ACTION_MACRO) ;
      ("DEFINE_ARRAY", PATCH_DEFINE_ARRAY) ;
      ("DEFINE_ASSOCIATIVE_ARRAY", DEFINE_ASSOCIATIVE_ARRAY) ;
      ("DEFINE_MACRO_ACTION", DEFINE_ACTION_MACRO) ;
      ("DEFINE_MACRO_PATCH", DEFINE_PATCH_MACRO) ;
      ("DEFINE_PATCH_MACRO", DEFINE_PATCH_MACRO) ;
      ("DELETE_BYTES", DELETE_BYTES);
      ("DEPRECATED", DEPRECATED);
      ("DESIGNATED", DESIGNATED);
      ("EDIT_SAV_FILE", EDIT_SAV_FILE) ;
      ("ELSE", ELSE) ;
      ("END", END) ;
      ("EQUIP", EQUIP);
      ("EVALUATE_REGEXP", EVALUATE_REGEXP);
      ("EXACT_MATCH", EXACT_MATCH);
      ("EXTEND",EXTEND_BOTTOM) ;
      ("EXTEND_BOTTOM", EXTEND_BOTTOM) ;
      ("EXTEND_BOTTOM_REGEXP", EXTEND_BOTTOM_REGEXP) ;
      ("EXTEND_TOP", EXTEND_TOP) ;
      ("EXTEND_TOP_REGEXP", EXTEND_TOP_REGEXP) ;
      ("EXTEND_MOS", EXTEND_MOS);
      ("EVALUATE_BUFFER", EVALUATE_BUFFER) ;
      ("FAIL", FAIL);
      ("FILE_IS_IN_COMPRESSED_BIF",FILE_IS_IN_COMPRESSED_BIF);
      ("FIRST", FIRST) ;
      ("FOR", FOR) ;
      ("FORBID_COMPONENT", FORBID_COMPONENT) ;
      ("FORBID_FILE", FORBID_FILE) ;
      ("FORCED_SUBCOMPONENT", FORCED_SUBCOMPONENT) ;
      ("FROM", FROM) ;
      ("GAME_IS", GAME_IS) ;
      ("GET_DIRECTORY_ARRAY", GET_DIRECTORY_ARRAY) ;
      ("GET_FILE_ARRAY", GET_FILE_ARRAY) ;
      ("GET_STRREF", GET_STRREF) ;
      ("GLOB", GLOB);
      ("GROUP", GROUP) ;
      ("IDS_OF_SYMBOL", IDS_OF_SYMBOL) ;
      ("IF", IF) ;
      ("IF_EVAL", IF_EVAL) ;
      ("IF_FILE_EXISTS", IF_FILE_EXISTS) ;
      ("IF_SIZE_IS", IF_SIZE_IS) ;
      ("IN", IN) ;
      ("INCLUDE", INCLUDE) ;
      ("ACTION_INCLUDE", INCLUDE) ;
      ("PATCH_INCLUDE", PATCH_INCLUDE) ;
      ("INNER_ACTION", INNER_ACTION) ;
      ("INNER_PATCH", INNER_PATCH) ;
      ("INNER_PATCH_FILE", INNER_PATCH_FILE) ;
      ("INNER_PATCH_SAVE", INNER_PATCH_SAVE) ;
      ("INSERT_2DA_ROW", INSERT_2DA_ROW) ;
      ("INSERT_BYTES", INSERT_BYTES);
      ("INSERT_FILE", INSERT_FILE);
      ("INSTALL_BY_DEFAULT", INSTALL_BY_DEFAULT) ;
      ("IS_AN_INT", IS_AN_INT);
      ("I_S_I", IF_SIZE_IS) ;
      ("LANGUAGE", LANGUAGE) ;
      ("LAST", LAST) ;
      ("LAUNCH_ACTION_MACRO", LAUNCH_ACTION_MACRO) ;
      ("LAUNCH_PATCH_MACRO", LAUNCH_PATCH_MACRO) ;
      ("LAUNCH_MACRO_PATCH", LAUNCH_PATCH_MACRO) ;
      ("LAUNCH_MACRO_ACTION", LAUNCH_ACTION_MACRO) ;
      ("LOAD", LOAD) ;
      ("LOAD_TRA", LOAD_TRA) ;
      ("LOCAL_SET", LOCAL_SET) ;
      ("LOCAL_SPRINT", LOCAL_SPRINT) ;
      ("LOCAL_TEXT_SPRINT", LOCAL_TEXT_SPRINT) ;
      ("MENU_STYLE", MENU_STYLE) ;
      ("MKDIR", MKDIR) ;
      ("MOD_IS_INSTALLED", MOD_IS_INSTALLED) ;
      ("MODDER", MODDER) ;
      ("NO_IF_EVAL_BUG", NO_IF_EVAL_BUG);
      ("NO_LOG_RECORD", NO_LOG_RECORD) ;
      ("NULL", NULL) ;
      ("OUTER_FOR", OUTER_FOR) ;
      ("OUTER_INNER_PATCH", OUTER_PATCH) ;
      ("OUTER_INNER_PATCH_SAVE", OUTER_PATCH_SAVE) ;
      ("OUTER_PATCH", OUTER_PATCH) ;
      ("OUTER_PATCH_SAVE", OUTER_PATCH_SAVE) ;
      ("OUTER_SET", OUTER_SET) ;
      ("OUTER_SPRINT", OUTER_SPRINT) ;
      ("OUTER_TEXT_SPRINT", OUTER_TEXT_SPRINT) ;
      ("OUTER_WHILE", OUTER_WHILE);
	    ("PATCH_BASH_FOR", PATCH_BASH_FOR) ;
	    ("PATCH_DEFINE_ARRAY", PATCH_DEFINE_ARRAY) ;
	    ("PATCH_PHP_EACH", PATCH_PHP_EACH) ;
	    ("PATCH_FOR_EACH", PATCH_FOR_EACH) ;
      ("PATCH_GAM", PATCH_GAM) ;
      ("PATCH_IF", PATCH_IF) ;
      ("PATCH_SILENT", PATCH_SILENT) ;
      ("PATCH_PRINT", PATCH_PRINT);
      ("PATCH_VERBOSE", PATCH_VERBOSE);
      ("PHP_EACH", PATCH_PHP_EACH) ;
      ("SPRINT", SPRINT);
      ("SNPRINT", SNPRINT);
      ("PRINT", PRINT);
      ("PRETTY_PRINT_2DA", PRETTY_PRINT_2DA);
      ("QUOTE", QUOTE);
      ("RANDOM", RANDOM);
      ("RANDOM_SEED", RANDOM_SEED);
      ("PATCH_RANDOM_SEED", PATCH_RANDOM_SEED);
      ("PATCH_READLN", PATCH_READLN);
      ("READ_2DA_ENTRIES_NOW", READ_2DA_ENTRIES_NOW) ;
      ("READ_2DA_ENTRY", READ_2DA_ENTRY) ;
      ("READ_2DA_ENTRY_FORMER", READ_2DA_ENTRY_FORMER) ;
      ("READ_ASCII", READ_ASCII);
      ("READ_STRREF", READ_STRREF);
      ("READ_BYTE", READ_BYTE) ;
      ("READ_SBYTE", READ_SBYTE) ;
      ("READ_SSHORT", READ_SSHORT) ;
      ("READ_LONG", READ_LONG) ;
      ("READ_SHORT", READ_SHORT) ;
      ("REINCLUDE", REINCLUDE) ;
      ("ACTION_REINCLUDE", REINCLUDE) ;
      ("PATCH_REINCLUDE", PATCH_REINCLUDE) ;
      ("REMOVE_CRE_ITEM", REMOVE_CRE_ITEM) ;
      ("REMOVE_KNOWN_SPELL", REMOVE_KNOWN_SPELL) ;
      ("REMOVE_MEMORIZED_SPELL", REMOVE_MEMORIZED_SPELL) ;
      ("REMOVE_STORE_ITEM", REMOVE_STORE_ITEM) ;
      ("REPLACE", REPLACE) ;
      ("REPLACE_BCS_BLOCK", REPLACE_BCS_BLOCK) ;
      ("REPLACE_BCS_BLOCK_REGEXP", REPLACE_BCS_BLOCK_REGEXP) ;
      ("REPLACE_CRE_ITEM", REPLACE_CRE_ITEM);
      ("REPLACE_EVALUATE", REPLACE_EVALUATE) ;
      ("REPLACE_TEXTUALLY", REPLACE_TEXTUALLY) ;
      ("REQUIRE_COMPONENT", REQUIRE_COMPONENT) ;
      ("REQUIRE_FILE", REQUIRE_FILE) ;
      ("REQUIRE_PREDICATE", REQUIRE_PREDICATE) ;
      ("R_B_B", REPLACE_BCS_BLOCK) ;
      ("R_B_B_RE", REPLACE_BCS_BLOCK_REGEXP) ;
      ("SAY", SAY) ;
      ("SAY_EVALUATED", SAY_EVALUATED) ;
      ("SCRIPT_STYLE", SCRIPT_STYLE) ;
      ("SET", SET);
      ("SET_2DA_ENTRY", SET_2DA_ENTRY) ;
      ("SET_2DA_ENTRY_LATER", SET_2DA_ENTRY_LATER) ;
      ("SET_2DA_ENTRIES_NOW", SET_2DA_ENTRIES_NOW) ;
      ("SILENT", SILENT) ;
      ("SPACES", SPACES) ;
      ("STATE_WHICH_SAYS", STATE_WHICH_SAYS) ;
      ("STRING_COMPARE", STRING_COMPARE) ;
      ("STRING_COMPARE_CASE", STRING_COMPARE_CASE) ;
      ("STRING_EQUAL", STRING_EQUAL) ;
      ("STRING_EQUAL_CASE", STRING_EQUAL_CASE) ;
      ("STRING_COMPARE_REGEXP", STRING_MATCHES_REGEXP) ;
      ("STRING_MATCHES_REGEXP", STRING_MATCHES_REGEXP) ;
      ("STRING_CONTAINS_REGEXP", STRING_CONTAINS_REGEXP) ;
      ("STRING_SET", STRING_SET) ;
      ("STRING_SET_EVALUATE", STRING_SET_EVALUATE) ;
      ("STRING_SET_RANGE", STRING_SET_RANGE) ;
      ("STR_CMP", STRING_COMPARE) ;
      ("SUBCOMPONENT", SUBCOMPONENT) ;
      ("SUB_COMPONENT", SUBCOMPONENT) ;
      ("TEXT_SPRINT", TEXT_SPRINT) ;
      ("THEN", THEN) ;
      ("TO_LOWER", TO_LOWER) ;
      ("TO_UPPER", TO_UPPER) ;
      ("TWOHANDED", TWOHANDED);
      ("UNINSTALL", UNINSTALL) ;
      ("UNLESS", UNLESS) ;
      ("USING", USING) ;
      ("VARIABLE_IS_SET", VARIABLE_IS_SET) ;
      ("VERBOSE", VERBOSE) ;
      ("WHILE", WHILE) ;
      ("WRITE_ASCII", WRITE_ASCII) ;
      ("WRITE_ASCII_TERMINATE", WRITE_ASCII_TERMINATED) ;
      ("WRITE_ASCIIT", WRITE_ASCII_TERMINATED) ;
      ("WRITE_BYTE", WRITE_BYTE) ;
      ("WRITE_EVALUATED_ASCII", WRITE_EVALUATED_ASCII) ;
      ("WRITE_ASCIIE", WRITE_EVALUATED_ASCII) ;
      ("WRITE_FILE", WRITE_FILE) ;
      ("WRITE_LONG", WRITE_LONG) ;
      ("WRITE_SHORT", WRITE_SHORT) ;
      
      ("ITM_V10_HEADERS", ITM_V10_HEADERS) ;
      ("ITM_V10_GEN_EFFECTS", ITM_V10_GEN_EFFECTS) ;
      ("WMP_AREAS", WMP_AREAS) ;
      ("WMP_LINKS", WMP_LINKS) ;


      ("ITM_V10_HEAD_EFFECTS", ITM_V10_HEAD_EFFECTS) ;

      (* predicates *)
      ("FILE_EXISTS", FILE_EXISTS ) ;
      ("FILE_MD5", FILE_MD5 ) ;
      ("FILE_EXISTS_IN_GAME", FILE_EXISTS_IN_GAME ) ;
      ("FILE_SIZE", FILE_SIZE ) ;
      ("FILE_CONTAINS", FILE_CONTAINS ) ;
      ("FILE_CONTAINS_EVALUATED", FILE_CONTAINS_EVALUATED ) ;
      ("AND", AND) ;
      ("OR", OR) ;
      ("NOT", NOT) ;

      ("BAND", BAND) ;
      ("BOR", BOR) ;
      ("BNOT", BNOT) ;
      ("BXOR", BXOR) ;
      ("BLSL", BLSL) ;
      ("BLSR", BLSR) ;
      ("BASR", BASR) ;
    ]


let newlexicon = Hashtbl.create 211
let _ = List.iter
    (fun (key) -> Hashtbl.add newlexicon key true)
    [
(*
PUT LEXICON *)
    ("CRE_V10_EFFECTS");
    ("DEFINE_ARRAY");
    ("PATCH_DEFINE_ARRAY");
    ("README");
    ("PATCH_SILENT");
    ("GLOB");
    ("COUNT_REGEXP_INSTANCES");
    ("OUTER_WHILE");
    ("STR_EQ");
    ("STRING_EQUAL_CASE");
    ("ON_MISMATCH");
    ("COMPRESS_INTO_VAR");
    ("EXISTING");
    ("PATCH_ABORT");
    ("NOTEQUALS");
    ("READ_2DA_ENTRY");
    ("GTE");
    ("MINUS_EQUALS");
    ("ALWAYS");
    ("REMOVE_KNOWN_SPELLS");
    ("PATCH_WARN");
    ("ARE_V10_DOOR_OPEN_CELL_VERTICES");
    ("REMOVE_CRE_ITEM");
    ("DELETE");
    ("SORT_ARRAY_INDICES");
    ("ABS");
    ("R_B_B_RE");
    ("REPLACE_BCS_BLOCK_REGEXP");
    ("CLEAR_INLINED");
    ("IS_SILENT");
    ("TWOHANDED");
    ("APPEND_OUTER");
    ("FROM");
    ("ARE_V10_ENTRANCES");
    ("SPL_V10_GEN_EFFECTS");
    ("LOCAL_SPRINT");
    ("EQUALS");
    ("LABEL");
    ("ADD_SCHOOL");
    ("COUNT_2DA_ROWS");
    ("LPF");
    ("LAUNCH_FUNCTION_PATCH");
    ("LAUNCH_PATCH_FUNCTION");
    ("COLON");
    ("VARIABLE_IS_IN_ARRAY");
    ("WMP_AREAS");
    ("EQUALSGREATER");
    ("AT_UNINSTALL_EXIT");
    ("EVAL");
    ("EVALUATE_BUFFER");
    ("LOCAL_TEXT_SPRINT");
    ("SET");
    ("COMPRESS_REPLACE_FILE");
    ("COMPILE");
    ("LPM");
    ("LAUNCH_MACRO_PATCH");
    ("LAUNCH_PATCH_MACRO");
    ("OUTER_SPRINTF");
    ("ON_DISABLE");
    ("REPLACE");
    ("REMOVE_MEMORIZED_SPELLS");
    ("WRITE_ASCIIL");
    ("WRITE_ASCII_LIST");
    ("GET_RESOURCE_ARRAY");
    ("BLSL_EQUALS");
    ("MOD_IS_INSTALLED");
    ("CLEAR");
    ("CRE_V10_KNOWN_SPELLS");
    ("REBUILD_CRE_FILE");
    ("BAND");
    ("BAND");
    ("IS_AN_INT");
    ("SCRIPT_STYLE");
    ("DECOMPRESS_INTO_VAR");
    ("THEN");
    ("BLSR_EQUALS");
    ("METADATA");
    ("DOLLARS");
    ("PATCH_BASH_FOR");
    ("INSERT_2DA_ROW");
    ("FORBID_COMPONENT");
    ("LAM");
    ("LAUNCH_MACRO_ACTION");
    ("LAUNCH_ACTION_MACRO");
    ("INNER_ACTION");
    ("APPLY_BCS_PATCH_OR_COPY");
    ("OUTER_SPRINT");
    ("DEFINE_FUNCTION_ACTION");
    ("DEFINE_ACTION_FUNCTION");
    ("PATCH_READLN");
    ("INNER_PATCH_SAVE");
    ("INSTALL_ORDER");
    ("READ_ASCII");
    ("ALTER_TLK_RANGE");
    ("QUOTE");
    ("DECOMPRESS_REPLACE_FILE");
    ("LAST");
    ("NOT");
    ("NOT");
    ("TO_LOWER");
    ("PATCH_PRINT");
    ("BEFORE");
    ("ADD_MEMORIZED_SPELL");
    ("DEFINE_DIMORPHIC_FUNCTION");
    ("ACTION_INCLUDE");
    ("INCLUDE");
    ("GET_STRREF_S");
    ("PATCH_TIME");
    ("LTE");
    ("ACTION_DEFINE_ASSOCIATIVE_ARRAY");
    ("FILE_IS_IN_COMPRESSED_BIFF");
    ("FILE_IS_IN_COMPRESSED_BIF");
    ("ACTION_TRY");
    ("CRE_V10_SPELL_MEM");
    ("STATE_WHICH_SAYS");
    ("BUT_ONLY");
    ("BUT_ONLY_IF_IT_CHANGES");
    ("PATCH_INCLUDE");
    ("ADD_MAP_NOTE");
    ("SSHORT_AT");
    ("SUB_COMPONENT");
    ("SUBCOMPONENT");
    ("SPL_V10_HEADERS");
    ("STO_V10_DRINKS");
    ("ACTION_PHP_EACH");
    ("REPLACE_EVALUATE");
    ("INSTALL_BY_DEFAULT");
    ("QUICK_MENU");
    ("REQUIRE_PREDICATE");
    ("LOAD_TRA");
    ("READ_SLONG");
    ("AT_NOW");
    ("TITLE");
    ("READ_SBYTE");
    ("EQUALSEQUALS");
    ("VARIABLE_IS_SET");
    ("GET_FILE_ARRAY");
    ("CLEAR_EVERYTHING");
    ("REFACTOR_TRIGGER");
    ("DECOMPILE_DLG_TO_D");
    ("ADD_SPELL");
    ("WHILE");
    ("TIMES");
    ("SET_BG2_PROFICIENCY");
    ("READ_STRREF_F");
    ("ACTION_TO_LOWER");
    ("INDEX");
    ("SPACES");
    ("APPEND_COL");
    ("STRING_SET_RANGE");
    ("RINDEX_BUFFER");
    ("WRITE_ASCII");
    ("NO_LOG_RECORD");
    ("AND");
    ("AND");
    ("FILE_CONTAINS");
    ("AT_INTERACTIVE_UNINSTALL_EXIT");
    ("TEXT_SPRINT");
    ("AT_EXIT");
    ("STO_V10_CURES");
    ("AT_INTERACTIVE_NOW");
    ("INT_VAR");
    ("DEFINED_AS_FUNCTION");
    ("ARE_V10_DOOR_CLOSED_CELL_VERTICES");
    ("DECOMPRESS_INTO_FILE");
    ("OUTER_INNER_PATCH");
    ("OUTER_PATCH");
    ("TRA_ENTRY_EXISTS");
    ("OUTER_SNPRINT");
    ("APPEND_FILE");
    ("BIFF_IS_COMPRESSED");
    ("DECOMPILE_BCS_TO_BAF");
    ("ARE_V10_REGION_VERTICES");
    ("MENU_STYLE");
    ("SIZE_OF_FILE");
    ("REMOVE_STORE_ITEM");
    ("MODDER");
    ("OR");
    ("OR");
    ("ALTER_TLK_LIST");
    ("COMPRESS_INTO_FILE");
    ("ITM_V10_HEAD_EFFECTS");
    ("CLEAR_IDS_MAP");
    ("FORBID_FILE");
    ("EXTEND_BOTTOM_REGEXP");
    ("EXACT");
    ("REFACTOR_BAF_TRIGGER");
    ("BACKUP");
    ("ADD_CRE_ITEM");
    ("CLEAR_ARRAY");
    ("PATCH_CLEAR_ARRAY");
    ("COPY_EXISTING_REGEXP");
    ("CASE_SENSITIVE");
    ("ALTER_TLK");
    ("DEFAULT");
    ("ASK_EVERY_COMPONENT");
    ("LPAREN");
    ("PATCH_DEFINE_ASSOCIATIVE_ARRAY");
    ("DEFINE_ASSOCIATIVE_ARRAY");
    ("GET_OFFSET_ARRAY2");
    ("SNPRINT");
    ("STR_CMP");
    ("STRING_COMPARE");
    ("READ_2DA_ENTRIES_NOW");
    ("IF_EXISTING");
    ("FILE_SIZE");
    ("CRE_V10_ITEMS");
    ("RESOURCE_CONTAINS");
    ("WMP_SOUTH_LINKS");
    ("REMOVE_MEMORIZED_SPELL");
    ("ARE_V10_CONTAINERS");
    ("SPRINTF");
    ("TIMES_EQUALS");
    ("EXTEND_BOTTOM");
    ("OR_EQUALS");
    ("ARE_V10_DOOR_CLOSED_OUTLINE_VERTICES");
    ("WMP_EAST_LINKS");
    ("ACTION_CLEAR_ARRAY");
    ("ADD_SECTYPE");
    ("NO_IF_EVAL_BUG");
    ("MANAGED");
    ("WMP_LINKS");
    ("ARE_V91_ACTORS");
    ("COPY_KIT");
    ("ALLOW_MISSING");
    ("PLUS_EQUALS");
    ("END");
    ("TIMESTIMES");
    ("PATCH_VERBOSE");
    ("ANY");
    ("QUESTION");
    ("BXOR_EQUALS");
    ("OUTER_SET_IDS_SYMBOL_OF_INT");
    ("ARE_V10_SPAWN_POINTS");
    ("EDIT_SAV_FILE");
    ("REM");
    ("MODULO");
    ("IN");
    ("COPY_LARGE");
    ("WHEN");
    ("IF");
    ("DEFINE_MACRO_PATCH");
    ("DEFINE_PATCH_MACRO");
    ("DIVIDE_EQUALS");
    ("GET_STRREF");
    ("DELETE_BYTES");
    ("APPEND_COL_OUTER");
    ("COPY");
    ("FILE_MD5");
    ("EVALUATE_BUFFER_SPECIAL");
    ("DESIGNATED");
    ("STO_V10_ITEMS_SOLD");
    ("WRITE_FILE");
    ("IF_EVAL");
    ("BLSL");
    ("BLSL");
    ("ADD_GAM_NPC");
    ("ADD_GAME_NPC");
    ("PATCH_GAM");
    ("LANGUAGE");
    ("STRING_CONTAINS_REGEXP");
    ("DECOMPRESS_BIFF");
    ("CLEAR_MEMORY");
    ("BOR");
    ("BOR");
    ("ACTION_TIME");
    ("EXTEND_TOP");
    ("ITM_V10_HEADERS");
    ("LOOKUP_IDS_SYMBOL_OF_INT");
    ("SET_IDS_SYMBOL_OF_INT");
    ("PATCH_RANDOM_SEED");
    ("FILE_CONTAINS_EVALUATED");
    ("ALWAYS_ASK");
    ("READ_STRREF_S");
    ("CLEAR_CODES");
    ("CRE_V10_SPELL_MEM_INFO");
    ("ACTION_FOR_EACH");
    ("ARE_V10_AMBIENTS");
    ("AFTER");
    ("A_B_P");
    ("APPLY_BCS_PATCH");
    ("RANDOM");
    ("READ_2DA_ENTRY_FORMER");
    ("READ_SHORT");
    ("VALID_SCRIPT_ACTIONS");
    ("REQUIRE_FILE");
    ("ACTION_MATCH");
    ("SPL_V10_HEAD_EFFECTS");
    ("STRING_COMPARE_REGEXP");
    ("STRING_MATCHES_REGEXP");
    ("WRITE_LONG");
    ("ADD_KNOWN_SPELL");
    ("BLSR");
    ("BLSR");
    ("UNLESS");
    ("I_S_I");
    ("IF_SIZE_IS");
    ("ACTION_BASH_FOR");
    ("GAME_IS");
    ("READ_BYTE");
    ("NULL");
    ("NOGLOB");
    ("ARE_V10_REGIONS");
    ("ARE_V10_CONTAINER_VERTICES");
    ("MINUS_MINUS");
    ("DEFINE_FUNCTION_PATCH");
    ("DEFINE_PATCH_FUNCTION");
    ("RET_ARRAY");
    ("VERBOSE");
    ("ACTION_SORT_ARRAY_INDICES");
    ("ARE_V10_ITEMS");
    ("LONG_AT");
    ("PATCH_FAIL");
    ("AS");
    ("DECOMPILE_AND_PATCH");
    ("BYTE_AT");
    ("AT");
    ("UNINSTALL");
    ("CACHE");
    ("ACTION_DEFINE_ARRAY");
    ("PATCH_WITH_SCOPE");
    ("ACTION_READLN");
    ("AT_INTERACTIVE_EXIT");
    ("GLOBAL");
    ("NEXT_STRREF");
    ("DISABLE_FROM_KEY");
    ("GET_STRREF_F");
    ("FILE_EXISTS");
    ("RESOLVE_STR_REF");
    ("ARE_V10_ACTORS");
    ("SEMICOLON");
    ("ADD_JOURNAL");
    ("COPY_RANDOM");
    ("DIVIDE");
    ("STRING_SET");
    ("ARE_V10_DOORS");
    ("WARN");
    ("OUTER_SET");
    ("TO_UPPER");
    ("DEFINED_AS_INLINED");
    ("MKDIR");
    ("COUNT_2DA_COLS");
    ("NUMERICALLY");
    ("WRITE_ASCIIE");
    ("WRITE_EVALUATED_ASCII");
    ("INDEX_BUFFER");
    ("BXOR");
    ("BXOR");
    ("EQUIP");
    ("CREATE");
    ("OUTER_INNER_PATCH_SAVE");
    ("OUTER_PATCH_SAVE");
    ("ADD_PROJECTILE");
    ("SHORT_AT");
    ("READ_STRREF");
    ("EXTEND_TOP_REGEXP");
    ("PLUS_PLUS");
    ("INSERT_BYTES");
    ("PATCH_MATCH");
    ("WRITE_ASCIIT");
    ("WRITE_ASCII_TERMINATE");
    ("WRITE_ASCII_TERMINATED");
    ("COMPILE_BAF_TO_BCS");
    ("GT");
    ("ENGINE_IS");
    ("RPAREN");
    ("ITM_V10_GEN_EFFECTS");
    ("ADD_AREA_TYPE");
    ("REPLACE_CRE_ITEM");
    ("PATCH_REINCLUDE");
    ("PATCH_LOG");
    ("VALID_SCRIPT_TRIGGERS");
    ("MOVE");
    ("LOCAL_SET");
    ("INSERT_FILE");
    ("ACTION_REINCLUDE");
    ("REINCLUDE");
    ("COPY_EXISTING");
    ("APPEND_FILE_EVALUATE");
    ("READ_STRREF_FS");
    ("REFACTOR_D_TRIGGER");
    ("STR_VAR");
    ("AND_EQUALS");
    ("ARE_V10_DOOR_OPEN_OUTLINE_VERTICES");
    ("REMOVE_CRE_ITEMS");
    ("TEXT");
    ("ELSE");
    ("GET_STRREF_FS");
    ("SET_2DA_ENTRIES_NOW");
    ("PATCH_IF");
    ("GROUP");
    ("IF_EXISTS");
    ("GAME_INCLUDES");
    ("WRITE_BYTE");
    ("ACTION_GET_STRREF_FS");
    ("BASR");
    ("CLEAR_ARRAYS");
    ("ARE_V10_ANIMATIONS");
    ("READ_LONG");
    ("AT_UNINSTALL");
    ("FAIL");
    ("LEXICOGRAPHICALLY");
    ("FOR");
    ("REQUIRE_COMPONENT");
    ("OUTER_FOR");
    ("STRING_SET_EVALUATE");
    ("ACTION_GET_STRREF_F");
    ("FORCED_SUBCOMPONENT");
    ("DEPRECATED");
    ("ABORT");
    ("GET_OFFSET_ARRAY");
    ("SET_2DA_ENTRY_LATER");
    ("VERSION");
    ("WMP_NORTH_LINKS");
    ("ACTION_GET_STRREF");
    ("ACTION_TO_UPPER");
    ("DEFINE_MACRO_ACTION");
    ("DEFINE_ACTION_MACRO");
    ("SOURCE_BIFF");
    ("APPEND");
    ("STRING_CONCAT");
    ("PATCH_RERAISE");
    ("WMP_WEST_LINKS");
    ("MINUS");
    ("ACTION_IF");
    ("PATCH_WITH_TRA");
    ("REMOVE_KNOWN_SPELL");
    ("UNINSTALL_ORDER");
    ("ACTION_RERAISE");
    ("REPLACE_TEXTUALLY");
    ("WITH_TRA");
    ("PHP_EACH");
    ("PATCH_PHP_EACH");
    ("STO_V10_ITEMS_PURCHASED");
    ("WITH_SCOPE");
    ("ADD_STORE_ITEM");
    ("INNER_PATCH_FILE");
    ("USING");
    ("FILE_EXISTS_IN_GAME");
    ("SAY_EVALUATED");
    ("LT");
    ("PRINT");
    ("SPRINT");
    ("PRETTY_PRINT_2DA");
    ("BNOT");
    ("BNOT");
    ("SAY");
    ("STRING_COMPARE_CASE");
    ("RET");
    ("GET_DIRECTORY_ARRAY");
    ("NOMOVE");
    ("COMPILE_D_TO_DLG");
    ("BUFFER_LENGTH");
    ("REGISTER_UNINSTALL");
    ("MAKE_BIFF");
    ("BIFF");
    ("EVALUATE_REGEXP");
    ("ADD_MUSIC");
    ("LOAD");
    ("BEGIN");
    ("REMOVE_CRE_EFFECTS");
    ("KEEP_CRLF");
    ("SILENT");
    ("RINDEX");
    ("SBYTE_AT");
    ("COPY_ALL_GAM_FILES");
    ("STRING_EQUAL");
    ("LOG");
    ("SLONG_AT");
    ("PLUS");
    ("READ_SSHORT");
    ("REMOVE_2DA_ROW");
    ("SET_2DA_ENTRY");
    ("LAF");
    ("LAUNCH_FUNCTION_ACTION");
    ("LAUNCH_ACTION_FUNCTION");
    ("INNER_PATCH");
    ("PATCH_TRY");
    ("WITH");
    ("ADD_IF_MISSING");
    ("COMMA");
    ("STRING_LENGTH");
    ("AT_INTERACTIVE_UNINSTALL");
    ("IDS_OF_SYMBOL");
    ("DIRECTORY_EXISTS");
    ("FIRST");
    ("ADD_KIT");
    ("RANDOM_SEED");
    ("R_B_B");
    ("REPLACE_BCS_BLOCK");
    ("ID_OF_LABEL");
    ("AUTO_TRA");
    ("OUTER_TEXT_SPRINT");
    ("WRITE_SHORT");
    ("EXACT_MATCH");
    ("PATCH_FOR_EACH");
    ("ACTION_GET_STRREF_S");
    ("AUTO_EVAL_STRINGS");
    ("CASE_INSENSITIVE");
    ("EXTEND_MOS");
    ("SUPPORT");
    ("AUTHOR")
    ]
(*
** Buffer processor
*)




}

let decdigit = ['0'-'9']
let octdigit = ['0'-'7']
let letter = ['a' - 'z' 'A'-'Z']

let blank = [' ' '\012' '\r']

rule initial = parse
  "/*"  { adj lexbuf ; let _ = comment lexbuf in initial lexbuf}
| "//"  { adj lexbuf ; endline lexbuf }
| blank	{ adj lexbuf ; initial lexbuf}
| '\t'  { tab (); initial lexbuf }
| '\n'  { newline (); initial lexbuf }
| '('   { adj lexbuf ; LPAREN }
| ')'   { adj lexbuf ; RPAREN }
| '?'   { adj lexbuf ; QUESTION }
| '$'   { adj lexbuf ; DOLLARS }
| ':'   { adj lexbuf ; COLON }
| ';'   { adj lexbuf ; SEMICOLON }
| '+'   { adj lexbuf ; PLUS }
| '-'   { adj lexbuf ; MINUS }
| '*'   { adj lexbuf ; TIMES }
| "**"   { adj lexbuf ; TIMESTIMES }
| '/'   { adj lexbuf ; DIVIDE }
| '='   { adj lexbuf ; EQUALS }
| '>'   { adj lexbuf ; GT }
| '<'   { adj lexbuf ; LT }
| '+'   { adj lexbuf ; PLUS }
| '^'   { adj lexbuf ; STRING_CONCAT }

| "+="  { adj lexbuf ; PLUS_EQUALS }
| "-="  { adj lexbuf ; MINUS_EQUALS }
| "*="  { adj lexbuf ; TIMES_EQUALS }
| "/="  { adj lexbuf ; DIVIDE_EQUALS }
| "|="  { adj lexbuf ; OR_EQUALS }
| "&="  { adj lexbuf ; AND_EQUALS }
| "<<=" { adj lexbuf ; BLSL_EQUALS }
| ">>=" { adj lexbuf ; BLSR_EQUALS }
| "^^=" { adj lexbuf ; BXOR_EQUALS }

| "!"   { adj lexbuf ; NOT }
| "&"  { adj lexbuf ; BAND }
| "|"  { adj lexbuf ; BOR }
| "^^" { adj lexbuf ; BXOR }
| "&&"  { adj lexbuf ; AND }
| "||"  { adj lexbuf ; OR }
| "<<"  { adj lexbuf ; BLSL }
| ">>"  { adj lexbuf ; BLSR }
| "`"   { adj lexbuf ; BNOT }

| ">="   { adj lexbuf ; GTE }
| "<="   { adj lexbuf ; LTE }
| "=>"   { adj lexbuf ; EQUALSGREATER }
| "=="  { adj lexbuf ; EQUALSEQUALS }
| "!="  { adj lexbuf ; NOTEQUALS }
| "["[^']']*"]" { str_adj lexbuf ; SOUND(remove_trailing_space(strip (string_of lexbuf))) }
| "~"[^'~']*"~"
| '"'[^'"']*'"'
| '%'[^'%']*'%'  { str_adj lexbuf ; STRING(strip (string_of lexbuf)) }
| ['0'-'9''A'-'Z''a'-'z''_']['0'-'9''A'-'Z''a'-'z''#''_''-''.']* {
    adj lexbuf ; let str = string_of lexbuf in
		match (Hashtbl.mem lexicon str, Hashtbl.mem newlexicon str) with
		| true, false -> raise Not_found
		| _, true -> Hashtbl.find lexicon str
		| false, false -> STRING str }
| '#'['-']?['0'-'9']+ { adj lexbuf ;
      let str = string_of lexbuf in
      let str = String.sub str 1 ((String.length str) - 1) in
      STRING_REF((int_of_string str)) }
| '!'['-']?['0'-'9']+ { adj lexbuf ;
      let str = string_of lexbuf in
      let str = String.sub str 1 ((String.length str) - 1) in
      FORCED_STRING_REF((int_of_string str)) }
| '@'['-']?['0'-'9']+ { adj lexbuf ;
      let str = string_of lexbuf in
      let str = String.sub str 1 ((String.length str) - 1) in
      TRANS_REF((int_of_string str)) }
| "~~~~~" { adj lexbuf ; let buf = Buffer.create 255 in widestring buf lexbuf }
| "<<<<<<<<" [' ']* ([^'\n''\r']* as name) ('\r'?)'\n' {
  adj lexbuf ;
  let buf = Buffer.create 10240 in
  inlined name buf lexbuf }
| eof   { EOF }
| _	{ lex_error (Printf.sprintf "invalid character [%s]\n HINT: Don't use MS Word to edit your .tp2 files - use a text editor." (string_of
lexbuf)) }
and comment = parse
      "*/"	{ adj lexbuf ; () }
|     '\n'      { newline (); comment lexbuf }
|     "/*"      { adj lexbuf ; let _ = comment lexbuf in comment lexbuf }
|     eof       { lex_error "unterminated comment" }
|     _ 	{ adj lexbuf ; comment lexbuf }
and widestring buf = parse
|     "~~~~~"    { adj lexbuf ; STRING(Buffer.contents buf) }
|     eof        { lex_error "unterminated ~~~~~ string" }
|     '\n'       { newline (); Buffer.add_char buf '\n';widestring buf lexbuf}
|     _          { adj lexbuf ; let str = string_of lexbuf in
                   Buffer.add_string buf str ; widestring buf lexbuf }
and inlined name buf = parse
|     ">>>>>>>>"{ adj lexbuf ;
                  INLINED_FILE(name,(Buffer.contents buf)) }
|     eof       { lex_error "unterminated inlined file" }
|     '\n'      { newline (); Buffer.add_char buf '\n' ;
                  inlined name buf lexbuf }
|     _         { adj lexbuf ;
                  let str = string_of lexbuf in
                  Buffer.add_string buf str ;
                  inlined name buf lexbuf }
and endline = parse
        '\n' 			{ newline (); initial lexbuf}
|	_			{ adj lexbuf ; endline lexbuf}
|       eof                     { EOF }
